# Generated by Django 6.0 on 2026-02-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fileshare', '0002_recently_shared'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recently_shared',
        ),
    ]
