# Generated by Django 6.0 on 2026-02-23 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fileshare', '0004_alter_sharefile_unique_together'),
        ('Main', '0003_files_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharefile',
            unique_together={('shared_to', 'file')},
        ),
    ]
