# Generated by Django 6.0 on 2026-01-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='extension',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
